version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservas
      MYSQL_USER: app
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: fastapi_container
    command: uvicorn Backend.api.user:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: