version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./Backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/reservas
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  frontend:
    image: nginx:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
  
  rabbitmq:
    build: ./RabbitMQ
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  rabbitmq_data:
