version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./Backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/reservas
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  frontend:
    image: node:16
    container_name: npx-frontend
    command: sh -c "cd /app/frontend && npx serve -s"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api

volumes:
  db_data:
