# Utiliza la imagen base oficial de RabbitMQ con la gestión activada
FROM rabbitmq:3-management

# Instala Python y pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Copia el script de Python al contenedor
COPY subscriber.py /app/subscriber.py
COPY requirements.txt .

# Instala las dependencias necesarias (si las hay)
# COPY requirements.txt /app/requirements.txt
# RUN pip3 install --no-cache-dir -r /app/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
# Comando para ejecutar RabbitMQ y el script de Python
CMD ["bash", "-c", "rabbitmq-server & sleep 10 && python3 /app/subscriber.py"]
